obj-y += rohc_decomp.o
obj-y += rohc_decomp_k_out_n.o
obj-y += decomp_uncomp.o
obj-y += rohc_decomp_wlsb.o
obj-y += decomp_ip.o
obj-y += rohc_decomp_packet.o
obj-y += rohc_decomp_profile_v1.o
obj-y += rohc_decomp_v1_packet.o
obj-y += decomp_udp.o
obj-y += decomp_tcp.o
obj-y += decomp_tcp_clist.o

obj-y += rohc_decomp_v2_common.o
obj-y += decomp_udp_v2.o
obj-y += decomp_rtp_clist.o
obj-y += decomp_rtp_v2.o
obj-y += decomp_ip_v2.o
