

obj-y += rohc_comp.o
obj-y += rohc_comp_hash.o
obj-y += rohc_comp_ipv4_hash.o
obj-y += comp_uncomp.o
obj-y += rohc_comp_wlsb.o
obj-y += dynamic_field_bh.o
obj-y += rohc_comp_profile_v1.o
obj-y += rohc_comp_v1_packet.o
obj-y += rohc_comp_packet.o
obj-y += comp_udp.o
obj-y += comp_tcp.o
obj-y += comp_tcp_clist.o


obj-y += rohc_comp_v2_common.o
obj-y += comp_udp_v2.o
obj-y += comp_rtp_clist.o
obj-y += comp_rtp_v2.o
obj-y += comp_ip_v2.o

